language: node_js
env:
  global:
    - 'SFTP_USER=[user]'
    - 'SFTP_PASSWORD=[password]'
    - 'SFTP_KEY=[base64-encoded-rsa-key]'
after_success: 'curl -T app.js -u $SFTP_USER:$SFTP_PASSWORD sftp://s27.mydevil.net/public_nodejs/'
node_js:
  - 10
branches:
  only:
    - master
install:
  - npm install
services:
  - mongodb
script:
  - npm test
notifications:
  email:
    recipients:
      - mail@mateuszjablonski.com
    on_success: change
    on_failure: always
