language: node_js
env:
  global:
    - 'SFTP_USER=[user]'
    - 'SFTP_PASSWORD=[password]'
    - 'SFTP_KEY=[base64-encoded-rsa-key]'
after_success:
  - find . -type d \( -path "./.*" -o -path "./node_modules" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} sftp://s27.mydevil.net/ --user ${SFTP_USER}:${SFTP_PASSWORD} \;
node_js:
  - 10
branches:
  only:
    - master
install:
  - npm install
services:
  - mongodb
script:
  - npm test
notifications:
  email:
    recipients:
      - mail@mateuszjablonski.com
    on_success: change
    on_failure: always
