language: node_js
node_js:
  - 10
branches:
  only:
    - master
install:
  - npm install
services:
  - mongodb
script:
  - npm test
notifications:
  email:
    recipients:
      - mail@mateuszjablonski.com
    on_success: change
    on_failure: always
