language: node_js
node_js:
  - 10
sudo: false
branches:
  only:
    - master
install:
  - npm install
services:
  - mongodb
script:
  - npm test
addons:
  ssh_known_hosts:
    - s27.mydevil.net
before_install:
  - openssl aes-256-cbc -K $encrypted_917e46d95efc_key -iv $encrypted_917e46d95efc_iv
    -in ./.travis/deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key woodpecker@s27.mydevil.net pwd
deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: mateuszjablonski-api
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/* -e ssh -i ./deploy_key woodpecker@s27.mydevil.net:~/domains/api.mateuszjablonski.com/public_nodejs/public
    on:
      branch: master
notifications:
  email:
    recipients:
      - mail@mateuszjablonski.com
    on_success: change
    on_failure: always
